# Generated by Django 5.1.3 on 2025-03-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0002_alter_table_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('g', 'Gram'), ('ml', 'Milliliter'), ('chai', 'Chai'), ('gói', 'Gói'), ('hộp', 'Hộp'), ('lon', 'Lon')], max_length=5),
        ),
    ]
