# Generated by Django 5.1.3 on 2025-05-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0002_chathistory_alter_inventorylog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
