# Generated by Django 5.1.3 on 2025-03-15 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0004_alter_bestsellingproduct_report_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, through='web_01.IngredientProduct', to='web_01.ingredient'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy'), ('completed', 'Đã hoàn thành')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='web_01.table'),
        ),
    ]
