# Generated by Django 5.1.3 on 2025-05-09 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0004_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshift',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='status',
        ),
        migrations.AddField(
            model_name='workshift',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ShiftRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('morning', 'Sáng'), ('afternoon', 'Chiều'), ('evening', 'Tối')], max_length=10)),
                ('is_off', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_registrations', to='web_01.employee')),
            ],
            options={
                'db_table': 'shift_registration',
                'unique_together': {('employee', 'date', 'shift_type')},
            },
        ),
    ]
