# Generated by Django 5.1.3 on 2025-03-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0006_product_created_at_product_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
