# Generated by Django 5.1.3 on 2025-05-24 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0006_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'Sáng'), ('afternoon', 'Chiều'), ('evening', 'Tối'), ('allday', 'Cả Ngày')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='web_01.table'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'Sáng'), ('afternoon', 'Chiều'), ('evening', 'Tối'), ('allday', 'Cả Ngày')], max_length=10),
        ),
    ]
