# Generated by Django 5.1.3 on 2025-03-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0008_alter_category_name_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Ngưng hoạt động')], default='active', max_length=10),
        ),
    ]
