# Generated by Django 5.1.3 on 2025-03-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0009_alter_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa giải quyết'), ('in_progress', 'Đang làm'), ('completed', 'Hoàn thành'), ('cancelled', 'Hủy')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
