# Generated by Django 5.1.3 on 2025-03-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0010_alter_order_status_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ'), ('in_progress', 'Đang làm'), ('completed', 'Xong'), ('cancelled', 'Hủy')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ'), ('in_progress', 'Đang làm'), ('completed', 'Xong'), ('cancelled', 'Hủy')], default='pending', max_length=15),
        ),
    ]
