# Generated by Django 5.1.3 on 2025-03-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0011_alter_order_status_alter_orderdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'Trống'), ('occupied', 'Sử dụng'), ('reserved', 'Đã đặt')], default='available', max_length=10),
        ),
    ]
