# Generated by Django 5.1.3 on 2025-03-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0012_alter_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='hour',
            field=models.TimeField(null=False),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='date',
            field=models.DateField(null=False),
        ),
    ]
