# Generated by Django 5.1.3 on 2025-04-01 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0013_tablereservation_hour_alter_tablereservation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('morning', 'Sáng'), ('afternoon', 'Chiều'), ('evening', 'Tối')], max_length=10)),
                ('duration', models.DecimalField(decimal_places=2, default=4.0, max_digits=4)),
                ('status', models.CharField(choices=[('worked', 'Đã làm'), ('off', 'Nghỉ')], default='worked', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshifts', to='web_01.employee')),
            ],
            options={
                'db_table': 'work_shift',
                'unique_together': {('employee', 'date', 'shift_type')},
            },
        ),
    ]
