# Generated by Django 5.1.3 on 2025-04-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0014_workshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
