# Generated by Django 5.1.3 on 2025-04-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0015_invoice_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản'), ('card', 'Thẻ')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ'), ('in_progress', 'Đang làm'), ('completed', 'Hoàn thành'), ('cancelled', 'Hủy')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ'), ('in_progress', 'Đang làm'), ('completed', 'Hoàn thành'), ('cancelled', 'Hủy')], default='pending', max_length=15),
        ),
    ]
