# Generated by Django 5.1.3 on 2025-04-18 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0016_alter_invoice_payment_method_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_01.session'),
        ),
    ]
