# Generated by Django 5.1.3 on 2025-04-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0017_notification_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='session',
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_status', 'Order Status'), ('promotion', 'Promotion'), ('reminder', 'Reminder'), ('custom', 'Custom')], max_length=15),
        ),
    ]
