# Generated by Django 5.1.3 on 2025-04-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0019_inventorylog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='stock_after',
            field=models.IntegerField(default=0),
        ),
    ]
