# Generated by Django 5.1.3 on 2025-04-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0020_inventorylog_stock_after'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorylog',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='stock_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='stock_after',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
