# Generated by Django 5.1.3 on 2025-04-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0021_alter_inventorylog_options_inventorylog_stock_before_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
