# Generated by Django 5.1.3 on 2025-04-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0022_chathistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chathistory',
            table='chat_history',
        ),
    ]
