# Generated by Django 5.1.3 on 2025-04-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0023_alter_chathistory_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_status', 'Order Status'), ('promotion', 'Promotion'), ('reminder', 'Reminder'), ('custom', 'Custom'), ('payment', 'Payment')], max_length=15),
        ),
    ]
