# Generated by Django 5.1.3 on 2025-04-27 13:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0024_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avartar_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avartar_url'),
        ),
    ]
