# Generated by Django 5.1.3 on 2025-05-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0025_employee_avartar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('g', 'Gram'), ('ml', 'Milliliter'), ('chai', 'Chai'), ('gói', 'Gói'), ('hộp', 'Hộp'), ('lon', 'Lon'), ('cai', 'Cái'), ('lang', 'Lạng'), ('trai', 'Trái'), ('hop', 'Hộp'), ('o', 'Ổ'), ('cu', 'Củ'), ('lit', 'Lít'), ('ml', 'Ml'), ('chai', 'Chai'), ('quả', 'Quả')], max_length=5),
        ),
    ]
