# Generated by Django 5.1.3 on 2025-05-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0026_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='type',
            field=models.CharField(choices=[('import', 'Nhập kho'), ('export', 'Xuất kho'), ('sell', 'Bán hàng'), ('adjustment', 'Điều chỉnh')], max_length=15),
        ),
    ]
