# Generated by Django 5.1.3 on 2025-05-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0027_alter_inventorylog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
