# Generated by Django 5.1.3 on 2025-05-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0029_employee_role_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='table',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
